rootProject.name = 'edubridge-os'

include 'backend:core'
include 'backend:shared'
include 'backend:identity'
include 'backend:academic'
include 'backend:career'
include 'backend:financial'
include 'backend:institution'
include 'backend:communication'
include 'backend:analytics'
include 'backend:ai'
include 'backend:integration'
include 'backend:learning-services'
include 'backend:student-services'
include 'backend:tests'
